import type { Metadata } from "next";
import "./globals.css";

// Temporarily removed font imports due to network limitations in the test environment
const geistSans = {
  variable: "--font-geist-sans"
};

const geistMono = {
  variable: "--font-geist-mono"
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
